/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.TrabajadorDAO;
import entidades.Trabajador;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrj
 */
public class ListadoTrabajadores extends javax.swing.JFrame {

  
  ArrayList<Trabajador> trabajadores = null;
  
  
  /**
   * Creates new form ListadoTrabajadores
   */
  public ListadoTrabajadores() {
    initComponents();
    //cierra la ventana NuevoTrabajador pero deja abierta la del Menu
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tblTrabajadores = new javax.swing.JTable();
    txtRut = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tblTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null}
      },
      new String [] {
        "RUT", "Nombre", "Apellido", "Edad", "Cargo", "Sexo", "¿Es Extranjero?"
      }
    ));
    jScrollPane1.setViewportView(tblTrabajadores);

    txtRut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtRutActionPerformed(evt);
      }
    });

    btnBuscar.setText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnBuscar)
            .addGap(126, 126, 126))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(btnEliminar)
            .addGap(115, 115, 115))))
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(67, 67, 67)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBuscar))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEliminar)
        .addContainerGap(40, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
     // TODO add your handling code here:
  }//GEN-LAST:event_txtRutActionPerformed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    this.listar();
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    // Esto nos dice el numero de fila seleccionado
    int indice = tblTrabajadores.getSelectedRow();
    // obtenemos del arraylist el trabajador mediante su indice
    Trabajador trabajador = this.trabajadores.get(indice);
    
    TrabajadorDAO tDAO = new TrabajadorDAO();
    
    
    try {
      if(tDAO.eliminarTrabajador(trabajador.getRut())){
        JOptionPane.showMessageDialog(this, "Eliminado correctamente");
      } else {
        JOptionPane.showMessageDialog(this, "No se ha podido eliminar");
      }
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
    
    this.listar();
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void listar(){
    TrabajadorDAO tDAO = new TrabajadorDAO();
    
    try {
      
      
      if(txtRut.getText().isEmpty()){
        trabajadores = tDAO.listarTrabajadores();
      } else {
        trabajadores = tDAO.buscarPorRut(txtRut.getText());
        
        if(trabajadores.size() == 0){
          JOptionPane.showMessageDialog(this, "No se ha encontrado nada con el RUT: " + txtRut.getText());
        }
      }
      
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("rut");
      modelo.addColumn("nombre");
      modelo.addColumn("apellido");
      modelo.addColumn("edad");
      modelo.addColumn("cargo");
      modelo.addColumn("sexo");
      modelo.addColumn("esExtranjero");
      
      for(Trabajador trabajadore : trabajadores){
        String[] fila = new String[7];
        fila[0] = trabajadore.getRut();
        fila[1] = trabajadore.getNombre();
        fila[2] = trabajadore.getApellido();
        fila[3] = String.valueOf(trabajadore.getEdad());
        fila[4] = trabajadore.getCargo();
        if(trabajadore.isSexo()){
          fila[5] = "masculino";
        } else {
          fila[5] = "femenino";
        }
        if(trabajadore.isExtranjero()){
          fila[6] = "Si";
        } else {
          fila[6] = "No";
        }
        modelo.addRow(fila);
      }
      
      tblTrabajadores.setModel(modelo);
      
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ListadoTrabajadores().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblTrabajadores;
  private javax.swing.JTextField txtRut;
  // End of variables declaration//GEN-END:variables
}
