/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import dao.TrabajadorDAO;
import entidades.Trabajador;
import javax.swing.JFrame;

/**
 *
 * @author adrj
 */
public class NuevoTrabajador extends javax.swing.JFrame {

  /**
   * Creates new form NuevoTrabajador
   */
  public NuevoTrabajador() {
    initComponents();
    //cierra la ventana NuevoTrabajador pero deja abierta la del Menu
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    lblRut = new javax.swing.JLabel();
    txtRut = new javax.swing.JTextField();
    lblNombre = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    lblApellido = new javax.swing.JLabel();
    txtApellido = new javax.swing.JTextField();
    lblEdad = new javax.swing.JLabel();
    spnEdad = new javax.swing.JSpinner();
    lblCargo = new javax.swing.JLabel();
    cboCargo = new javax.swing.JComboBox<>();
    lblSexo = new javax.swing.JLabel();
    rbtMasculino = new javax.swing.JRadioButton();
    rbtFemenino = new javax.swing.JRadioButton();
    chkEsExtranjero = new javax.swing.JCheckBox();
    btnGuardar = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lblRut.setText("RUT");

    lblNombre.setText("Nombre");

    lblApellido.setText("Apellido");

    lblEdad.setText("Edad");

    lblCargo.setText("Cargo");

    cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Asistente", "Vendedor" }));

    lblSexo.setText("Sexo");

    buttonGroup1.add(rbtMasculino);
    rbtMasculino.setSelected(true);
    rbtMasculino.setText("Masculino");

    buttonGroup1.add(rbtFemenino);
    rbtFemenino.setText("Femenino");

    chkEsExtranjero.setText("¿Es extrajero?");

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnLimpiar.setText("Limpiar");
    btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimpiarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(chkEsExtranjero)
            .addGap(90, 90, 90)
            .addComponent(btnLimpiar))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblRut)
              .addComponent(lblNombre)
              .addComponent(lblApellido)
              .addComponent(lblEdad)
              .addComponent(lblCargo)
              .addComponent(lblSexo))
            .addGap(46, 46, 46)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(rbtMasculino)
                .addGap(30, 30, 30)
                .addComponent(rbtFemenino))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtRut)
                .addComponent(txtNombre)
                .addComponent(txtApellido)
                .addComponent(spnEdad)
                .addComponent(cboCargo, 0, 105, Short.MAX_VALUE)))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        .addComponent(btnGuardar)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblRut)
          .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblNombre)
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblApellido)
          .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblEdad)
          .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCargo)
          .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblSexo)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(rbtMasculino)
            .addComponent(rbtFemenino)))
        .addGap(18, 18, 18)
        .addComponent(chkEsExtranjero)
        .addContainerGap(34, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardar)
          .addComponent(btnLimpiar))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    try {
      
      Trabajador t = new Trabajador();
      t.setRut(txtRut.getText());
      t.setNombre(txtNombre.getText());
      t.setApellido(txtApellido.getText());
      t.setEdad(Integer.parseInt(spnEdad.getValue().toString()));
      t.setCargo(cboCargo.getSelectedItem().toString());
      t.setSexo(rbtMasculino.isSelected());
      t.setExtranjero(chkEsExtranjero.isSelected());
      
      TrabajadorDAO tDAO = new TrabajadorDAO();
      
      if(tDAO.agregarTrabajador(t)){
        JOptionPane.showMessageDialog(this, "Guardado correctamente");
        this.limpiar();
      } else {
        JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
      }
   
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
       
    
  }//GEN-LAST:event_btnGuardarActionPerformed

  private void limpiar(){
    txtRut.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    spnEdad.setValue(0);
    cboCargo.setSelectedIndex(0);
    rbtMasculino.setSelected(true);
    chkEsExtranjero.setSelected(false);
  }
  
  private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    // TODO add your handling code here:
    this.limpiar();
  }//GEN-LAST:event_btnLimpiarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NuevoTrabajador().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGuardar;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox<String> cboCargo;
  private javax.swing.JCheckBox chkEsExtranjero;
  private javax.swing.JLabel lblApellido;
  private javax.swing.JLabel lblCargo;
  private javax.swing.JLabel lblEdad;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblRut;
  private javax.swing.JLabel lblSexo;
  private javax.swing.JRadioButton rbtFemenino;
  private javax.swing.JRadioButton rbtMasculino;
  private javax.swing.JSpinner spnEdad;
  private javax.swing.JTextField txtApellido;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtRut;
  // End of variables declaration//GEN-END:variables
}
